version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_USER=messaging_user
      - MYSQL_PASSWORD=secret123
      - MYSQL_DB=messaging_db
    ports:
      - "3306:3306"

  web:
    image: python:3.10
    container_name: web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
